### ISSUE TITLE
Move email sending outside of Doctrine subscriber

### ISSUE THREAD

**Issue by ld-web** [Damdam9388/web_library_front#54]
- At this time, when I load the fixtures, the app tries to send a confirmation email, because it's directly written inside the Doctrine subscriber

- It would be better to define your own `user.register` event and trigger it from all the places where a user is registered.
Then, define as well your own subscriber, plugged to this event.

See [this article](https://symfony.com/doc/current/components/event_dispatcher.html#creating-and-dispatching-an-event)

**Comment by Damdam9388** [comment]
The event dispatcher  has been set up and the send email methode has been move outside of doctrine
