### ISSUE TITLE
Axios request refactoring

### ISSUE THREAD

**Issue by ld-web** [Damdam9388/web_library_front#58]
Refactoring axios requests into one or two functions would represent a good improvement of the codebase.
That way, it would be unnecessary to duplicate the `config` object construction, as well as the token retrieval logic.

An interesting approach would be to instantiate an Axios object with `Axios.create` ([doc](https://github.com/axios/axios#axioscreateconfig)).

Finally, putting this or these method(s) into its own module (or, file) would give you the ability to fully isolate this feature. Easier to read, easier to maintain, easier to debug, shorter to write.

You can take this module as an inspiration (of course you'll have to rewrite/adapt it, it comes from a project I'm working on ^^) :

```js
import Axios from "axios";
import { apiPlatformApiEndpoint, tokenStorageName } from "./constants";
import i18n from "../i18n";

const getLoggedInstance = (baseUrl = apiPlatformApiEndpoint) => {
  const instance = getInstance(
    {
      Authorization: `Bearer ${window.localStorage.getItem(tokenStorageName)}`,
    },
    baseUrl
  );

  return instance;
};

export const getInstance = (
  headers = null,
  baseURL = apiPlatformApiEndpoint
) => {
  let config = {
    baseURL: baseURL,
  };

  let languageHeader = {
    "APP-LOCALE": i18n.language,
  };

  if (headers !== null) {
    config.headers = {
      ...headers,
      ...languageHeader,
    };
  } else {
    config.headers = {
      ...languageHeader,
    };
  }

  const instance = Axios.create(config);

  return instance;
};

export default getLoggedInstance;

```

I can then use `getLoggedInstance` wherever I need to make a request.
By the way, you can see I didn't export `getInstance` yet. It's simply because at this time, I don't need it. But, if I need it later, that's okay => I'll just export it for the other parts which might need it :)

**Comment by max1300** [comment]
done

![dab](https://user-images.githubusercontent.com/51815206/92133082-426fe580-ee08-11ea-941e-2e8432bcb359.jpg)
